name: LobbyBalancer-Server-Connector
main: de.simonsator.partyandfriends.serverconnector.playerbalancer.PBServerConnector
version: ${project.version}
author: Simonsator
depend: [LobbyBalancer, PartyAndFriends]